name: Website Deploy

on:
  push:
    paths:
      - '.website/**'   

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Sync .website to S3
        run: aws s3 sync ./.website s3://dishant-connected-bucket --delete
